//
// Created by kevinlad on 2021/6/10.
//

#ifndef SRC_CARLA_ROS_BRIDGE_CARLA_NAVIGATION_CARLA_DECISION_SRC_BT_NODES_ACTION_CRUISE_H_
#define SRC_CARLA_ROS_BRIDGE_CARLA_NAVIGATION_CARLA_DECISION_SRC_BT_NODES_ACTION_CRUISE_H_

#include "common.h"

// class Cruise {
//
//};

#endif //SRC_CARLA_ROS_BRIDGE_CARLA_NAVIGATION_CARLA_DECISION_SRC_BT_NODES_ACTION_CRUISE_H_
