before_script:
  - docker info 
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull harbor.isus.tech/carlasim/carla:0.9.10.1
  - docker pull harbor.isus.tech/osrf/ros:noetic-desktop-full-focal

build_image:
  script:
     - cd docker
     - docker build -t $CI_REGISTRY/carla-ros/carla-ros:$CI_COMMIT_BRANCH -f Dockerfile ./..
     - docker push $CI_REGISTRY/carla-ros/carla-ros:$CI_COMMIT_BRANCH
  retry: 2     
