before_script:
  - docker info 
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull harbor.isus.tech/carlasim/carla:0.9.10.1
  - docker pull harbor.isus.tech/osrf/ros:noetic-desktop-full-focal

build_image:
  script:
     - cd docker
     - docker build -t registry.gitlab.isus.tech/kevinlad/carla-ros/carla-ros:0.9.10.1-noetic -f Dockerfile ./..
     - docker push registry.gitlab.isus.tech/kevinlad/carla-ros-bridge/carla-ros:0.9.10.1-noetic