
#ifndef CARLA1S_ROS_CARLA1S_NAVIGATION_CARLA1S_PLANNING_CARLA1S_PATH_TRACKING_SRC_COMMON_CUBIC_SPLINE_H_
#define CARLA1S_ROS_CARLA1S_NAVIGATION_CARLA1S_PLANNING_CARLA1S_PATH_TRACKING_SRC_COMMON_CUBIC_SPLINE_H_

class CubicSpline {
 public:
  CubicSpline();

  void Gen2dSpline(const nav_msgs::Path &path);

};

#endif // CARLA1S_ROS_CARLA1S_NAVIGATION_CARLA1S_PLANNING_CARLA1S_PATH_TRACKING_SRC_COMMON_CUBIC_SPLINE_H_
