
#ifndef CARLA1S_ROS_CARLA_NAVIGATION_CARLA_DECISION_SRC_TYPES_H_
#define CARLA1S_ROS_CARLA_NAVIGATION_CARLA_DECISION_SRC_TYPES_H_

struct TrafficLights{
  std::uint32_t id;

};


#endif //CARLA1S_ROS_CARLA_NAVIGATION_CARLA_DECISION_SRC_TYPES_H_
